### PR TITLE
BlobStoreHealthCheck rewrite

### LINKED ISSUE #1: blobstore health check fails when it shouldn't
The [BlobStoreHealthCheck](https://github.com/commercehub-oss/dropwizard-jclouds/blob/master/dropwizard-jclouds-blobstore/src/main/java/com/commercehub/dropwizard/jclouds/blobstore/health/BlobStoreHealthCheck.java), as currently implemented, puts an object, checks if it exists, and if so, deletes it. If all of this happens successfully, the health check is considered healthy. For the aws-s3 blobstore implementation, when used with a bucket in [a region that does not support read-after-write consistency](http://aws.amazon.com/s3/faqs/#What_data_consistency_model_does_Amazon_S3_employ), such as the US Standard region, this health check often fails due to the fact that a get for an object is not guaranteed to succeed shortly after it is newly put.

This health check should be made more robust, perhaps by requiring that a seed file be placed on the bucket for testing reads, and a separate put is made to test writes. It may be advantageous to break this up into two health checks so that an application can choose to only use one if it does not need the other.

### PR DESCRIPTION
**Pull request by mhurne**
This will close #1 and #2

### CODE REVIEW

File: dropwizard-jclouds-blobstore/src/main/java/com/commercehub/dropwizard/jclouds/blobstore/health/BlobStoreHealthCheck.java [hunk 1]
```diff
@@ -3,44 +3,27 @@
...
-                                Payload payload,
-                                String contentType) {
-        this.blobStoreContext = blobStoreContext;
-        this.container = container;
-        this.blobName = blobNamePrefix + "/" + UUID.randomUUID();
-        this.payload = payload;
-        this.contentType = contentType;
+    public BlobStoreHealthCheck(BlobStoreContext blobStoreContext, String container) {
+        this.blobStoreContext = checkNotNull(blobStoreContext);
+        this.container = checkNotNull(container).trim();
```
Comment (joschi) [inline dropwizard-jclouds-blobstore/src/main/java/com/commercehub/dropwizard/jclouds/blobstore/health/BlobStoreHealthCheck.java]: While it's unusual, container names could contain leading or trailing white spaces and still be valid.

Comment (mhurne) [inline dropwizard-jclouds-blobstore/src/main/java/com/commercehub/dropwizard/jclouds/blobstore/health/BlobStoreHealthCheck.java]: Good to know - I'll remove the `trim`. Thanks!
